import React,{useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{Search,ShoppingBag,Heart,ArrowRight,Download,ShieldCheck,X,Menu}from'lucide-react';import'./styles.css';
const products=[
{id:1,name:'Sunday Reset Planner',cat:'Planners',price:8,badge:'Best Seller',icon:'✦',desc:'A calm weekly reset to plan priorities, routines and little joys.'},
{id:2,name:'Bloom & Grow Wall Art',cat:'Wall Art',price:6,badge:'New',icon:'❀',desc:'A soft botanical print designed to brighten a quiet corner.'},
{id:3,name:'Gentle Habits Tracker',cat:'Journaling',price:5,badge:'Popular',icon:'♡',desc:'A simple, encouraging habit tracker with room to reflect.'},
{id:4,name:'Daily Pages Journal',cat:'Journaling',price:7,badge:'Instant',icon:'✎',desc:'Undated daily pages for thoughts, plans, gratitude and notes.'},
{id:5,name:'Garden Party Cards',cat:'Party Printables',price:9,badge:'Favorite',icon:'❋',desc:'Pretty printable cards for garden parties, showers and celebrations.'},
{id:6,name:'Little Moments Planner',cat:'Planners',price:8,badge:'Best Seller',icon:'☼',desc:'A gentle planner for turning busy days into manageable moments.'}
];const cats=['All','Planners','Wall Art','Journaling','Party Printables'];
function App(){const[cat,setCat]=useState('All'),[q,setQ]=useState(''),[cart,setCart]=useState([]),[open,setOpen]=useState(false),[menu,setMenu]=useState(false);const filtered=useMemo(()=>products.filter(p=>(cat==='All'||p.cat===cat)&&(!q||p.name.toLowerCase().includes(q.toLowerCase())||p.cat.toLowerCase().includes(q.toLowerCase()))),[cat,q]);const add=p=>setCart(c=>[...c,p]);const total=cart.reduce((s,p)=>s+p.price,0);
return <><div className="promo">Instant digital downloads · Shop from anywhere</div><header><a className="brand" href="#">Marigold<span>Lane</span>Prints</a><button className="mobileMenu" onClick={()=>setMenu(!menu)}><Menu size={22}/></button><nav className={menu?'show':''}>{cats.slice(1).map(c=><button key={c} onClick={()=>{setCat(c);setMenu(false)}}>{c}</button>)}</nav><div className="headTools"><label className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search printables"/></label><button className="cartBtn" onClick={()=>setOpen(true)}><ShoppingBag size={19}/><span>{cart.length}</span></button></div></header>
<main><section className="hero"><div><p className="eyebrow">PRINTABLES FOR EVERYDAY MOMENTS</p><h1>Beautiful little things for your everyday life.</h1><p className="heroCopy">Thoughtfully designed planners, wall art, journals and party printables. Download instantly and make ordinary moments feel a little more lovely.</p><button className="primary" onClick={()=>document.getElementById('shop').scrollIntoView({behavior:'smooth'})}>Shop printables <ArrowRight size={17}/></button></div><div className="heroCard"><div className="paper"><span>✦</span><h3>Make room for<br/>what matters.</h3><small>MARIGOLD LANE PRINTS</small></div></div></section>
<section className="shop" id="shop"><div className="sectionHead"><div><p className="eyebrow">THE SHOP</p><h2>Find your next favorite printable.</h2></div><div className="filters">{cats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div></div><div className="grid">{filtered.map(p=><article className="product" key={p.id}><div className="preview"><span className="badge">{p.badge}</span><div className="previewPaper"><b>{p.icon}</b><h3>{p.name}</h3><small>{p.cat}</small></div><button className="heart"><Heart size={17}/></button></div><div className="productInfo"><div><h3>{p.name}</h3><p>{p.desc}</p></div><strong>${p.price.toFixed(2)}</strong></div><button className="add" onClick={()=>add(p)}>Add to cart</button></article>)}</div></section>
<section className="steps"><p className="eyebrow">EASY AS 1 · 2 · 3</p><h2>Printables without the waiting.</h2><div className="stepGrid"><div><b>01</b><h3>Choose your favorite</h3><p>Browse thoughtfully designed digital goods for planning, journaling, decorating and celebrating.</p></div><div><b>02</b><h3>Pay securely</h3><p>Checkout is designed for a quick, simple digital purchase through Paystack.</p></div><div><b>03</b><h3>Download instantly</h3><p>Your purchased files are delivered digitally, so there is no shipping box plotting against you.</p></div></div></section>
<section className="trust"><div><ShieldCheck size={23}/><span><b>Instant digital delivery</b><small>No physical item will be shipped.</small></span></div><div><Download size={23}/><span><b>Print at home</b><small>Use your favorite home or local print service.</small></span></div><div><Heart size={23}/><span><b>Made with care</b><small>Designed for real everyday moments.</small></span></div></section>
<section className="newsletter"><p className="eyebrow">A LITTLE NOTE FROM US</p><h2>Pretty printables, delivered to your inbox.</h2><p>New releases, seasonal collections and occasional free goodies.</p><form onSubmit={e=>{e.preventDefault();e.currentTarget.reset();alert('Thanks for joining MarigoldLanePrints!')}}><input required type="email" placeholder="Your email address"/><button className="primary">Join the list</button></form></section></main>
<footer><div className="brand">Marigold<span>Lane</span>Prints</div><p>Digital printables for everyday moments.</p><small>© 2026 MarigoldLanePrints · Digital products only</small></footer>
{open&&<div className="overlay" onClick={()=>setOpen(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setOpen(false)}><X/></button><h2>Your cart</h2>{cart.length===0?<p className="empty">Your cart is waiting patiently.</p>:<>{cart.map((p,i)=><div className="cartItem" key={i}><div><b>{p.name}</b><small>{p.cat}</small></div><span>${p.price.toFixed(2)}</span></div>)}<div className="total"><span>Total</span><b>${total.toFixed(2)}</b></div><button className="primary checkout" onClick={()=>window.location.href='/checkout'}>Checkout with Paystack <ArrowRight size={17}/></button></>}<p className="fine">Secure payment · Instant digital delivery</p></aside></div>}</>};createRoot(document.getElementById('root')).render(<App/>);